-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["AuthenticZ_Store_12"] = {{ name = "other", tiles = {"AuthenticZ_Store_8", "AuthenticZ_Store_10"} }}
overlayMap["AuthenticZ_Store_13"] = {{ name = "other", tiles = {"AuthenticZ_Store_9", "AuthenticZ_Store_11"} }}
overlayMap["AuthenticZ_Store_16"] = {{ name = "other", tiles = {"AuthenticZ_Store_18", "AuthenticZ_Store_18"} }}
overlayMap["AuthenticZ_Store_17"] = {{ name = "other", tiles = {"AuthenticZ_Store_19", "AuthenticZ_Store_19"} }}
overlayMap["AuthenticZ_Store_25"] = {{ name = "other", tiles = {"clothing_01_11", "clothing_01_19"} }}
overlayMap["AuthenticZ_Store_26"] = {{ name = "other", tiles = {"clothing_01_12", "clothing_01_20"} }}
overlayMap["AuthenticZ_Store_27"] = {{ name = "other", tiles = {"clothing_01_13", "clothing_01_21"} }}
overlayMap["AuthenticZ_Store_36"] = {{ name = "other", tiles = {"AuthenticZ_Store_32", "AuthenticZ_Store_34"} }}
overlayMap["AuthenticZ_Store_37"] = {{ name = "other", tiles = {"AuthenticZ_Store_33", "AuthenticZ_Store_35"} }}
overlayMap["Block_Trasher_0"] = {{ name = "other", tiles = {"Block_Trasher_8", "Block_Trasher_12"} }}
overlayMap["Block_Trasher_1"] = {{ name = "other", tiles = {"Block_Trasher_9", "Block_Trasher_13"} }}
overlayMap["Block_Trasher_2"] = {{ name = "other", tiles = {"Block_Trasher_10", "Block_Trasher_14"} }}
overlayMap["Block_Trasher_3"] = {{ name = "other", tiles = {"Block_Trasher_11", "Block_Trasher_15"} }}
overlayMap["Block_Trasher_24"] = {{ name = "other", tiles = {"food_01_0", "food_01_2"} }}
overlayMap["Block_Trasher_25"] = {{ name = "other", tiles = {"food_01_1", "food_01_3"} }}
overlayMap["Block_Trasher_40"] = {{ name = "other", tiles = {"food_02_8", "food_02_16"} }}
overlayMap["Block_Trasher_41"] = {{ name = "other", tiles = {"food_02_9", "food_02_17"} }}
overlayMap["Block_Trasher_42"] = {{ name = "other", tiles = {"food_02_9", "food_02_17"} }}
overlayMap["Block_Trasher_43"] = {{ name = "other", tiles = {"food_02_10", "food_02_18"} }}
overlayMap["Block_Trasher_44"] = {{ name = "other", tiles = {"food_02_11", "food_02_19"} }}
overlayMap["Block_Trasher_45"] = {{ name = "other", tiles = {"food_02_12", "food_02_20"} }}
overlayMap["Block_Trasher_46"] = {{ name = "other", tiles = {"food_02_12", "food_02_20"} }}
overlayMap["Block_Trasher_47"] = {{ name = "other", tiles = {"food_02_13", "food_02_21"} }}
overlayMap["Block_Trasher_60"] = {{ name = "other", tiles = {"Block_Trasher_56", "Block_Trasher_56"} }}
overlayMap["Block_Trasher_61"] = {{ name = "other", tiles = {"Block_Trasher_57", "Block_Trasher_57"} }}
overlayMap["Block_Trasher_62"] = {{ name = "other", tiles = {"Block_Trasher_58", "Block_Trasher_58"} }}
overlayMap["Block_Trasher_63"] = {{ name = "other", tiles = {"Block_Trasher_59", "Block_Trasher_59"} }}
overlayMap["Bookies_Store_12"] = {{ name = "other", tiles = {"Bookies_Store_8", "Bookies_Store_10"} }}
overlayMap["Bookies_Store_13"] = {{ name = "other", tiles = {"Bookies_Store_9", "Bookies_Store_11"} }}
overlayMap["Bookies_Store_14"] = {{ name = "other", tiles = {"Bookies_Store_18", "Bookies_Store_16"} }}
overlayMap["Bookies_Store_15"] = {{ name = "other", tiles = {"Bookies_Store_19", "Bookies_Store_17"} }}
overlayMap["Bookies_Store_22"] = {{ name = "other", tiles = {"Bookies_Store_20", "Bookies_Store_20"} }}
overlayMap["Bookies_Store_23"] = {{ name = "other", tiles = {"Bookies_Store_21", "Bookies_Store_21"} }}
overlayMap["Bookies_Store_26"] = {{ name = "other", tiles = {"Bookies_Store_24", "Bookies_Store_24"} }}
overlayMap["Bookies_Store_27"] = {{ name = "other", tiles = {"Bookies_Store_25", "Bookies_Store_25"} }}
overlayMap["Bookies_Store_30"] = {{ name = "other", tiles = {"Bookies_Store_28", "Bookies_Store_28"} }}
overlayMap["Bookies_Store_31"] = {{ name = "other", tiles = {"Bookies_Store_29", "Bookies_Store_29"} }}
overlayMap["Bookies_Store_38"] = {{ name = "other", tiles = {"Bookies_Store_28", "Bookies_Store_28"} }}
overlayMap["Bookies_Store_39"] = {{ name = "other", tiles = {"Bookies_Store_29", "Bookies_Store_29"} }}
overlayMap["Bookies_Store_42"] = {{ name = "other", tiles = {"Bookies_Store_40", "Bookies_Store_40"} }}
overlayMap["Bookies_Store_43"] = {{ name = "other", tiles = {"Bookies_Store_41", "Bookies_Store_41"} }}
overlayMap["Bookies_Store_44"] = {{ name = "other", tiles = {"Bookies_Store_48", "Bookies_Store_52"} }}
overlayMap["Bookies_Store_45"] = {{ name = "other", tiles = {"Bookies_Store_49", "Bookies_Store_53"} }}
overlayMap["Bookies_Store_46"] = {{ name = "other", tiles = {"Bookies_Store_50", "Bookies_Store_54"} }}
overlayMap["Bookies_Store_47"] = {{ name = "other", tiles = {"Bookies_Store_51", "Bookies_Store_55"} }}
overlayMap["Bookies_Store_60"] = {{ name = "other", tiles = {"Bookies_Store_56", "Bookies_Store_58"} }}
overlayMap["Bookies_Store_61"] = {{ name = "other", tiles = {"Bookies_Store_57", "Bookies_Store_59"} }}
overlayMap["DylansMusicStore_21"] = {{ name = "other", tiles = {"DylansMusicStore_9", "DylansMusicStore_13"} }}
overlayMap["DylansMusicStore_22"] = {{ name = "other", tiles = {"DylansMusicStore_10", "DylansMusicStore_14"} }}
overlayMap["DylansMusicStore_23"] = {{ name = "other", tiles = {"DylansMusicStore_11", "DylansMusicStore_15"} }}
overlayMap["DylansMusicStore_28"] = {{ name = "other", tiles = {"DylansMusicStore_24", "DylansMusicStore_26"} }}
overlayMap["DylansMusicStore_29"] = {{ name = "other", tiles = {"DylansMusicStore_25", "DylansMusicStore_27"} }}
overlayMap["DylansRandomFurniture03_54"] = {{ name = "other", tiles = {"DylansRandomFurniture03_52", "DylansRandomFurniture03_52"} }}
overlayMap["DylansRandomFurniture03_55"] = {{ name = "other", tiles = {"DylansRandomFurniture03_53", "DylansRandomFurniture03_53"} }}
overlayMap["DylansRandomFurniture03_60"] = {{ name = "other", tiles = {"DylansRandomFurniture03_62", "DylansRandomFurniture03_62"} }}
overlayMap["DylansRandomFurniture03_61"] = {{ name = "other", tiles = {"DylansRandomFurniture03_63", "DylansRandomFurniture03_63"} }}
overlayMap["DylansRandomFurniture04_13"] = {{ name = "other", tiles = {"DylansRandomFurniture04_12", "DylansRandomFurniture04_12"} }}
overlayMap["DylansRandomFurniture04_15"] = {{ name = "other", tiles = {"DylansRandomFurniture04_14", "DylansRandomFurniture04_14"} }}
overlayMap["DylansRandomFurniture04_17"] = {{ name = "other", tiles = {"DylansRandomFurniture04_16", "DylansRandomFurniture04_16"} }}
overlayMap["DylansRandomFurniture04_19"] = {{ name = "other", tiles = {"DylansRandomFurniture04_18", "DylansRandomFurniture04_18"} }}
overlayMap["DylansRandomFurniture04_25"] = {{ name = "other", tiles = {"DylansRandomFurniture04_24", "DylansRandomFurniture04_24"} }}
overlayMap["DylansRandomFurniture04_26"] = {{ name = "other", tiles = {"DylansRandomFurniture04_27", "DylansRandomFurniture04_27"} }}
overlayMap["appliances_refrigeration_01_16"] = {{ name = "other", tiles = {"food_01_90", "food_01_94"} }, { name = "other", tiles = {"food_02_90", "food_02_94"} }}
overlayMap["appliances_refrigeration_01_17"] = {{ name = "other", tiles = {"food_01_91", "food_01_95"} }, { name = "other", tiles = {"food_02_91", "food_02_95"} }}
overlayMap["appliances_refrigeration_01_18"] = {{ name = "other", tiles = {"food_01_88", "food_01_92"} }, { name = "other", tiles = {"food_02_88", "food_02_92"} }}
overlayMap["appliances_refrigeration_01_19"] = {{ name = "other", tiles = {"food_01_89", "food_01_93"} }, { name = "other", tiles = {"food_02_89", "food_02_93"} }}
overlayMap["appliances_refrigeration_01_22"] = {{ name = "other", tiles = {"food_01_54", "food_01_62"} }, { name = "other", tiles = {"food_02_54", "food_02_62"} }}
overlayMap["appliances_refrigeration_01_23"] = {{ name = "other", tiles = {"food_01_55", "food_01_63"} }, { name = "other", tiles = {"food_02_55", "food_02_63"} }}
overlayMap["appliances_refrigeration_01_40"] = {{ name = "other", tiles = {"food_01_54", "food_01_62"} }, { name = "other", tiles = {"food_02_54", "food_02_62"} }}
overlayMap["appliances_refrigeration_01_41"] = {{ name = "other", tiles = {"food_01_55", "food_01_63"} }, { name = "other", tiles = {"food_02_55", "food_02_63"} }}
overlayMap["carpentry_02_64"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["carpentry_02_65"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["carpentry_02_68"] = {{ name = "other", tiles = {"books&misc_01_56", "books&misc_01_58"} }, { name = "other", tiles = {"books&misc_02_56", "books&misc_02_58"} }}
overlayMap["carpentry_02_69"] = {{ name = "other", tiles = {"books&misc_01_57", "books&misc_01_59"} }, { name = "other", tiles = {"books&misc_02_57", "books&misc_02_59"} }}
overlayMap["d_furniture_bedroom_01_48"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["d_furniture_bedroom_01_49"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["d_furniture_bedroom_02_48"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["d_furniture_bedroom_02_49"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["d_furniture_bedroom_03_48"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["d_furniture_bedroom_03_49"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["d_furniture_bedroom_04_48"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["d_furniture_bedroom_04_49"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["d_furniture_bedroom_05_48"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["d_furniture_bedroom_05_49"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["furniture_shelving_01_0"] = {{ name = "other", tiles = {"books&misc_01_0", "books&misc_01_1"} }, { name = "other", tiles = {"books&misc_02_0", "books&misc_02_1"} }}
overlayMap["furniture_shelving_01_1"] = {{ name = "other", tiles = {"books&misc_01_2", "books&misc_01_4"} }, { name = "other", tiles = {"books&misc_02_2", "books&misc_02_4"} }}
overlayMap["furniture_shelving_01_2"] = {{ name = "other", tiles = {"books&misc_01_3", "books&misc_01_5"} }, { name = "other", tiles = {"books&misc_02_3", "books&misc_02_5"} }}
overlayMap["furniture_shelving_01_3"] = {{ name = "other", tiles = {"books&misc_01_8", "books&misc_01_10"} }, { name = "other", tiles = {"books&misc_02_8", "books&misc_02_10"} }}
overlayMap["furniture_shelving_01_4"] = {{ name = "other", tiles = {"books&misc_01_9", "books&misc_01_11"} }, { name = "other", tiles = {"books&misc_02_9", "books&misc_02_11"} }}
overlayMap["furniture_shelving_01_8"] = {{ name = "other", tiles = {"books&misc_01_0", "books&misc_01_1"} }}
overlayMap["furniture_shelving_01_9"] = {{ name = "other", tiles = {"books&misc_01_16", "books&misc_01_18"} }, { name = "other", tiles = {"books&misc_02_16", "books&misc_02_18"} }}
overlayMap["furniture_shelving_01_10"] = {{ name = "other", tiles = {"books&misc_01_17", "books&misc_01_19"} }, { name = "other", tiles = {"books&misc_02_17", "books&misc_02_19"} }}
overlayMap["furniture_shelving_01_16"] = {{ name = "other", tiles = {"books&misc_01_32", "books&misc_01_40"} }, { name = "other", tiles = {"books&misc_02_32", "books&misc_02_40"} }}
overlayMap["furniture_shelving_01_17"] = {{ name = "other", tiles = {"books&misc_01_33", "books&misc_01_41"} }, { name = "other", tiles = {"books&misc_02_33", "books&misc_02_41"} }}
overlayMap["furniture_shelving_01_18"] = {{ name = "other", tiles = {"books&misc_01_34", "books&misc_01_42"} }, { name = "other", tiles = {"books&misc_02_34", "books&misc_02_42"} }}
overlayMap["furniture_shelving_01_19"] = {{ name = "other", tiles = {"books&misc_01_35", "books&misc_01_43"} }, { name = "other", tiles = {"books&misc_02_35", "books&misc_02_43"} }}
overlayMap["furniture_shelving_01_20"] = {{ name = "other", tiles = {"books&misc_01_36", "books&misc_01_44"} }, { name = "other", tiles = {"books&misc_02_36", "books&misc_02_44"} }}
overlayMap["furniture_shelving_01_21"] = {{ name = "other", tiles = {"books&misc_01_37", "books&misc_01_45"} }, { name = "other", tiles = {"books&misc_02_37", "books&misc_02_45"} }}
overlayMap["furniture_shelving_01_22"] = {{ name = "other", tiles = {"books&misc_01_38", "books&misc_01_46"} }, { name = "other", tiles = {"books&misc_02_38", "books&misc_02_46"} }}
overlayMap["furniture_shelving_01_23"] = {{ name = "other", tiles = {"books&misc_01_39", "books&misc_01_47"} }, { name = "other", tiles = {"books&misc_02_39", "books&misc_02_47"} }}
overlayMap["furniture_shelving_01_24"] = {{ name = "other", tiles = {"books&misc_01_24", "books&misc_01_28"} }, { name = "other", tiles = {"books&misc_02_24", "books&misc_02_28"} }}
overlayMap["furniture_shelving_01_25"] = {{ name = "other", tiles = {"books&misc_01_25", "books&misc_01_29"} }, { name = "other", tiles = {"books&misc_02_25", "books&misc_02_29"} }}
overlayMap["furniture_shelving_01_26"] = {{ name = "other", tiles = {"books&misc_01_26", "books&misc_01_30"} }, { name = "other", tiles = {"books&misc_02_26", "books&misc_02_30"} }}
overlayMap["furniture_shelving_01_27"] = {{ name = "other", tiles = {"books&misc_01_27", "books&misc_01_31"} }, { name = "other", tiles = {"books&misc_02_27", "books&misc_02_31"} }}
overlayMap["furniture_shelving_01_28"] = {{ name = "other", tiles = {"books&misc_01_48", "books&misc_01_52"} }, { name = "other", tiles = {"books&misc_02_48", "books&misc_02_52"} }}
overlayMap["furniture_shelving_01_29"] = {{ name = "other", tiles = {"books&misc_01_49", "books&misc_01_53"} }, { name = "other", tiles = {"books&misc_02_49", "books&misc_02_53"} }}
overlayMap["furniture_shelving_01_30"] = {{ name = "other", tiles = {"books&misc_01_50", "books&misc_01_54"} }, { name = "other", tiles = {"books&misc_02_50", "books&misc_02_54"} }}
overlayMap["furniture_shelving_01_31"] = {{ name = "other", tiles = {"books&misc_01_51", "books&misc_01_55"} }, { name = "other", tiles = {"books&misc_02_51", "books&misc_02_55"} }}
overlayMap["furniture_shelving_01_32"] = {{ name = "other", tiles = {"books&misc_01_56", "books&misc_01_58"} }, { name = "other", tiles = {"books&misc_02_56", "books&misc_02_58"} }}
overlayMap["furniture_shelving_01_33"] = {{ name = "other", tiles = {"books&misc_01_57", "books&misc_01_59"} }, { name = "other", tiles = {"books&misc_02_57", "books&misc_02_59"} }}
overlayMap["furniture_shelving_01_34"] = {{ name = "other", tiles = {"books&misc_01_56", "books&misc_01_58"} }, { name = "other", tiles = {"books&misc_02_56", "books&misc_02_58"} }}
overlayMap["furniture_shelving_01_35"] = {{ name = "other", tiles = {"books&misc_01_57", "books&misc_01_59"} }, { name = "other", tiles = {"books&misc_02_57", "books&misc_02_59"} }}
overlayMap["furniture_shelving_01_36"] = {{ name = "other", tiles = {"books&misc_01_56", "books&misc_01_58"} }, { name = "other", tiles = {"books&misc_02_56", "books&misc_02_58"} }}
overlayMap["furniture_shelving_01_37"] = {{ name = "other", tiles = {"books&misc_01_57", "books&misc_01_59"} }, { name = "other", tiles = {"books&misc_02_57", "books&misc_02_59"} }}
overlayMap["furniture_shelving_01_40"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["furniture_shelving_01_41"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["furniture_shelving_01_44"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["furniture_shelving_01_45"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["furniture_storage_ddd_01_0"] = {{ name = "other", tiles = {"furniture_storage_ddd_01_8", "furniture_storage_ddd_01_16"} }}
overlayMap["furniture_storage_ddd_01_1"] = {{ name = "other", tiles = {"furniture_storage_ddd_01_9", "furniture_storage_ddd_01_17"} }}
overlayMap["furniture_storage_ddd_01_2"] = {{ name = "other", tiles = {"furniture_storage_ddd_01_10", "furniture_storage_ddd_01_18"} }}
overlayMap["furniture_storage_ddd_01_3"] = {{ name = "other", tiles = {"furniture_storage_ddd_01_11", "furniture_storage_ddd_01_19"} }}
overlayMap["furniture_storage_ddd_01_12"] = {{ name = "other", tiles = {"furniture_storage_ddd_01_20", "furniture_storage_ddd_01_28"} }}
overlayMap["furniture_storage_ddd_01_14"] = {{ name = "other", tiles = {"industry_dirkea_ddd_01_21", "industry_dirkea_ddd_01_31"} }, { name = "other", tiles = {"industry_dirkea_ddd_01_20", "industry_dirkea_ddd_01_23"} }}
overlayMap["furniture_storage_ddd_01_15"] = {{ name = "other", tiles = {"books&misc_01_57", "books&misc_01_59"} }, { name = "other", tiles = {"books&misc_02_57", "books&misc_02_59"} }}
overlayMap["furniture_storage_ddd_01_24"] = {{ name = "other", tiles = {"furniture_storage_ddd_01_32", "furniture_storage_ddd_01_40"} }}
overlayMap["furniture_storage_ddd_01_25"] = {{ name = "other", tiles = {"furniture_storage_ddd_01_33", "furniture_storage_ddd_01_41"} }}
overlayMap["furniture_storage_ddd_01_26"] = {{ name = "other", tiles = {"furniture_storage_ddd_01_34", "furniture_storage_ddd_01_42"} }}
overlayMap["furniture_storage_ddd_01_27"] = {{ name = "other", tiles = {"furniture_storage_ddd_01_35", "furniture_storage_ddd_01_43"} }}
overlayMap["furniture_storage_ddd_01_48"] = {{ name = "other", tiles = {"furniture_storage_ddd_01_59", "furniture_storage_ddd_01_59"} }}
overlayMap["furniture_storage_ddd_01_50"] = {{ name = "other", tiles = {"furniture_storage_ddd_01_60", "furniture_storage_ddd_01_60"} }}
overlayMap["furniture_storage_ddd_01_51"] = {{ name = "other", tiles = {"furniture_storage_ddd_01_60", "furniture_storage_ddd_01_60"} }}
overlayMap["furniture_storage_ddd_01_52"] = {{ name = "other", tiles = {"furniture_storage_ddd_01_59", "furniture_storage_ddd_01_59"} }}
overlayMap["furniture_storage_ddd_01_53"] = {{ name = "other", tiles = {"furniture_storage_ddd_01_61", "furniture_storage_ddd_01_61"} }}
overlayMap["furniture_storage_ddd_01_54"] = {{ name = "other", tiles = {"furniture_storage_ddd_01_62", "furniture_storage_ddd_01_62"} }}
overlayMap["furniture_storage_ddd_01_55"] = {{ name = "other", tiles = {"furniture_storage_ddd_01_63", "furniture_storage_ddd_01_63"} }}
overlayMap["hydrotiles_50"] = {{ name = "other", tiles = {"hydrotiles_49", "hydrotiles_48"} }}
overlayMap["hydrotiles_66"] = {{ name = "other", tiles = {"hydrotiles_67", "hydrotiles_69"} }}
overlayMap["hydrotiles_71"] = {{ name = "other", tiles = {"hydrotiles_52", "hydrotiles_55"} }}
overlayMap["industry_dirkea_ddd_01_12"] = {{ name = "other", tiles = {"industry_dirkea_ddd_01_20", "industry_dirkea_ddd_01_28"} }}
overlayMap["industry_dirkea_ddd_01_13"] = {{ name = "other", tiles = {"industry_dirkea_ddd_01_21", "industry_dirkea_ddd_01_29"} }}
overlayMap["industry_dirkea_ddd_01_14"] = {{ name = "other", tiles = {"industry_dirkea_ddd_01_22", "industry_dirkea_ddd_01_30"} }}
overlayMap["industry_dirkea_ddd_01_15"] = {{ name = "other", tiles = {"industry_dirkea_ddd_01_23", "industry_dirkea_ddd_01_31"} }}
overlayMap["industry_dirkea_ddd_01_24"] = {{ name = "other", tiles = {"industry_dirkea_ddd_01_32", "industry_dirkea_ddd_01_32"} }, { name = "other", tiles = {"industry_dirkea_ddd_01_40", "industry_dirkea_ddd_01_40"} }}
overlayMap["industry_dirkea_ddd_01_25"] = {{ name = "other", tiles = {"industry_dirkea_ddd_01_33", "industry_dirkea_ddd_01_33"} }, { name = "other", tiles = {"industry_dirkea_ddd_01_41", "industry_dirkea_ddd_01_41"} }}
overlayMap["industry_dirkea_ddd_01_26"] = {{ name = "other", tiles = {"industry_dirkea_ddd_01_34", "industry_dirkea_ddd_01_34"} }, { name = "other", tiles = {"industry_dirkea_ddd_01_42", "industry_dirkea_ddd_01_42"} }}
overlayMap["industry_dirkea_ddd_01_27"] = {{ name = "other", tiles = {"industry_dirkea_ddd_01_35", "industry_dirkea_ddd_01_35"} }, { name = "other", tiles = {"industry_dirkea_ddd_01_43", "industry_dirkea_ddd_01_43"} }}
overlayMap["industry_dirkea_ddd_01_37"] = {{ name = "other", tiles = {"industry_dirkea_ddd_01_52", "industry_dirkea_ddd_01_44"} }, { name = "other", tiles = {"industry_dirkea_ddd_01_53", "industry_dirkea_ddd_01_45"} }}
overlayMap["industry_dirkea_ddd_01_38"] = {{ name = "other", tiles = {"industry_dirkea_ddd_01_54", "industry_dirkea_ddd_01_46"} }, { name = "other", tiles = {"industry_dirkea_ddd_01_55", "industry_dirkea_ddd_01_47"} }}
overlayMap["industry_railroad_ddd_01_28"] = {{ name = "other", tiles = {"industry_railroad_ddd_01_30"} }}
overlayMap["industry_railroad_ddd_01_29"] = {{ name = "other", tiles = {"industry_railroad_ddd_01_31"} }}
overlayMap["industry_railroad_ddd_01_36"] = {{ name = "other", tiles = {"industry_railroad_ddd_01_21"} }}
overlayMap["industry_railroad_ddd_01_37"] = {{ name = "other", tiles = {"industry_railroad_ddd_01_22"} }}
overlayMap["industry_tk_02_25"] = {{ name = "other", tiles = {"container_overlays_tk_01_0", "container_overlays_tk_01_0"} }}
overlayMap["industry_tk_02_26"] = {{ name = "other", tiles = {"container_overlays_tk_01_1", "container_overlays_tk_01_1"} }}
overlayMap["location_business_distillery_01_0"] = {{ name = "other", tiles = {"location_business_distillery_01_1", "location_business_distillery_01_2"} }}
overlayMap["location_business_distillery_01_5"] = {{ name = "other", tiles = {"location_business_distillery_01_3", "location_business_distillery_01_4"} }}
overlayMap["location_shop_zippee_01_0"] = {{ name = "other", tiles = {"books_misc_02_104", "books_misc_02_108"} }}
overlayMap["location_shop_zippee_01_8"] = {{ name = "other", tiles = {"food_01_8", "food_01_16"} }, { name = "other", tiles = {"food_02_8", "food_02_16"} }}
overlayMap["location_shop_zippee_01_9"] = {{ name = "other", tiles = {"food_01_9", "food_01_17"} }, { name = "other", tiles = {"food_02_9", "food_02_17"} }}
overlayMap["location_shop_zippee_01_10"] = {{ name = "other", tiles = {"food_01_9", "food_01_17"} }, { name = "other", tiles = {"food_02_9", "food_02_17"} }}
overlayMap["location_shop_zippee_01_11"] = {{ name = "other", tiles = {"food_01_10", "food_01_18"} }, { name = "other", tiles = {"food_02_10", "food_02_18"} }}
overlayMap["location_shop_zippee_01_12"] = {{ name = "other", tiles = {"food_01_11", "food_01_19"} }, { name = "other", tiles = {"food_02_11", "food_02_19"} }}
overlayMap["location_shop_zippee_01_13"] = {{ name = "other", tiles = {"food_01_12", "food_01_20"} }, { name = "other", tiles = {"food_02_12", "food_02_20"} }}
overlayMap["location_shop_zippee_01_14"] = {{ name = "other", tiles = {"food_01_12", "food_01_20"} }, { name = "other", tiles = {"food_02_12", "food_02_20"} }}
overlayMap["location_shop_zippee_01_15"] = {{ name = "other", tiles = {"food_01_13", "food_01_21"} }, { name = "other", tiles = {"food_02_13", "food_02_21"} }}
overlayMap["location_shop_zippee_01_24"] = {{ name = "other", tiles = {"books&misc_01_12", "books&misc_01_20"} }, { name = "other", tiles = {"books&misc_02_12", "books&misc_02_20"} }}
overlayMap["location_shop_zippee_01_25"] = {{ name = "other", tiles = {"books&misc_01_13", "books&misc_01_21"} }, { name = "other", tiles = {"books&misc_02_13", "books&misc_02_21"} }}
overlayMap["location_shop_zippee_01_26"] = {{ name = "other", tiles = {"books&misc_01_14", "books&misc_01_22"} }, { name = "other", tiles = {"books&misc_02_14", "books&misc_02_22"} }}
overlayMap["location_shop_zippee_01_27"] = {{ name = "other", tiles = {"books&misc_01_15", "books&misc_01_23"} }, { name = "other", tiles = {"books&misc_02_15", "books&misc_02_23"} }}
overlayMap["trelai_tiles_01_72"] = {{ name = "other", tiles = {"trelai_tiles_01_80", "trelai_tiles_01_81"} }}
overlayMap["trelai_tiles_01_73"] = {{ name = "other", tiles = {"none", "trelai_tiles_01_80"} }}
overlayMap["trelai_tiles_01_74"] = {{ name = "other", tiles = {"trelai_tiles_01_82", "trelai_tiles_01_83"} }}
overlayMap["trelai_tiles_01_75"] = {{ name = "other", tiles = {"none", "trelai_tiles_01_83"} }}
overlayMap["trelai_tiles_01_84"] = {{ name = "other", tiles = {"trelai_tiles_01_148", "trelai_tiles_01_148"} }}
overlayMap["trelai_tiles_01_99"] = {{ name = "other", tiles = {"trelai_tiles_01_100", "trelai_tiles_01_102"} }}
overlayMap["trelai_tiles_01_103"] = {{ name = "other", tiles = {"trelai_tiles_01_101", "trelai_tiles_01_97"} }}
overlayMap["trelai_tiles_01_110"] = {{ name = "other", tiles = {"trelai_tiles_01_108", "trelai_tiles_01_104"} }}
overlayMap["trelai_tiles_01_111"] = {{ name = "other", tiles = {"trelai_tiles_01_109", "trelai_tiles_01_105"} }}
overlayMap["trelai_tiles_07_44"] = {{ name = "other", tiles = {"trelai_tiles_07_19", "trelai_tiles_07_17"} }}
overlayMap["trelai_tiles_07_45"] = {{ name = "other", tiles = {"trelai_tiles_07_44", "trelai_tiles_07_43"} }}
overlayMap["trelai_tiles_07_96"] = {{ name = "other", tiles = {"trelai_tiles_07_98"} }}
overlayMap["trelai_tiles_07_100"] = {{ name = "other", tiles = {"trelai_tiles_07_102"} }}
overlayMap["trelai_tiles_07_101"] = {{ name = "other", tiles = {"trelai_tiles_07_103"} }}

---Skizots Blockbuster Tiles
overlayMap["Skizot_tiles_16"] = {{ name = "other", tiles = {"Skizot_tiles_40", "Skizot_tiles_40"} }}
overlayMap["Skizot_tiles_17"] = {{ name = "other", tiles = {"Skizot_tiles_41", "Skizot_tiles_41"} }}
overlayMap["Skizot_tiles_18"] = {{ name = "other", tiles = {"Skizot_tiles_42", "Skizot_tiles_42"} }}
overlayMap["Skizot_tiles_19"] = {{ name = "other", tiles = {"Skizot_tiles_43", "Skizot_tiles_43"} }}
overlayMap["Skizot_tiles_20"] = {{ name = "other", tiles = {"Skizot_tiles_44", "Skizot_tiles_44"} }}
overlayMap["Skizot_tiles_21"] = {{ name = "other", tiles = {"Skizot_tiles_45", "Skizot_tiles_45"} }}
overlayMap["Skizot_tiles_22"] = {{ name = "other", tiles = {"Skizot_tiles_46", "Skizot_tiles_46"} }}
overlayMap["Skizot_tiles_23"] = {{ name = "other", tiles = {"Skizot_tiles_47", "Skizot_tiles_47"} }}
overlayMap["Skizot_tiles_54"] = {{ name = "other", tiles = {"Skizot_tiles_62", "Skizot_tiles_62"} }}
overlayMap["Skizot_tiles_55"] = {{ name = "other", tiles = {"Skizot_tiles_63", "Skizot_tiles_63"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
