require "TCMusicDefenitions"

	GlobalMusic["VinylBASILVALDEZSanaAyIkawNaNga"] = "tsarcraft_music_01_63"
	GlobalMusic["VinylBreathlessbySharonCuneta"] = "tsarcraft_music_01_63"
	GlobalMusic["VinylCan'tFindNoReasonbyLouieHeredia"] = "tsarcraft_music_01_63"
	GlobalMusic["VinylIDon'tNeedToSayILoveYoubyMartinNievera"] = "tsarcraft_music_01_63"
	GlobalMusic["VinylIsn'tSheLovelybyRaymondLauchengco"] = "tsarcraft_music_01_63"
	GlobalMusic["VinylJULIEVEGASomewhereInMyPast(LP)"] = "tsarcraft_music_01_63"
	GlobalMusic["VinylKUHLEDESMAIThinkI'mInLove"] = "tsarcraft_music_01_63"
	GlobalMusic["VinylLEASALONGAIfOnly(Lp1987)"] = "tsarcraft_music_01_63"
	GlobalMusic["VinylLovingYoubyGerryParaiso"] = "tsarcraft_music_01_63"
	GlobalMusic["VinylMARTINNIEVERAEachDayWithYou(Lp1984)"] = "tsarcraft_music_01_63"
	GlobalMusic["VinylMARTINNIEVERAHowCanI(LP1984)"] = "tsarcraft_music_01_63"
	GlobalMusic["VinylNEOCOLOURSMaybe(Lp1990)"] = "tsarcraft_music_01_63"
	GlobalMusic["VinylNEOCOLOURSTuloyPaRin(onVinyl)"] = "tsarcraft_music_01_63"
	GlobalMusic["VinylNONOYZUNIGAHaveIReallyLostYou(LP1982)"] = "tsarcraft_music_01_63"
	GlobalMusic["VinylOGIEALCASIDDitoSaPusoKo(LP)"] = "tsarcraft_music_01_63"
	GlobalMusic["VinylPa'NoNgayonDiNaKitaMahalbyCristyMendoza"] = "tsarcraft_music_01_63"
	GlobalMusic["VinylRIcSegretoLovingYou(1982)"] = "tsarcraft_music_01_63"
	GlobalMusic["VinylSHARONCUNETAEwan(1979)"] = "tsarcraft_music_01_63"
	GlobalMusic["VinylSinceYouSaidGoodbyebyRicSegreto"] = "tsarcraft_music_01_63"
	GlobalMusic["VinylVST&COMPANYIkawAngAkingMahal(Lp1978)"] = "tsarcraft_music_01_63"
	GlobalMusic["VinylVST&COMPANYIpagpatawad(Lp1978)"] = "tsarcraft_music_01_63"
	GlobalMusic["VinylZSAZSAPADILLAIkawLamang(Lp1986)"] = "tsarcraft_music_01_63"
	GlobalMusic["VinylZSAZSAPADILLAMambobola"] = "tsarcraft_music_01_63"

