require "TCMusicDefenitions"

	GlobalMusic["CassetteDINGDONGAVANZADOBastatKasamaKita(Cassette1989)"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteFRANCISMAGALONAColdSummerNights(Cassette1990)"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteGELLIDEBELEN&ANDREWEMrDJ(Cassette1991)"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteGINOPADILLAGustoKita(Cassette1990)"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteGINOPADILLAIBelieveInLove(Cassette1990)"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteJANNOGIBBSSana(Cassette1990)"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteJOHNMELOHanapHanapKita(Cassette1992)"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteMANILYNREYNESShakeItBaby(Cassette1992)"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteMELISSAGIBBSBakitBaGanyan[HQAudioCassette1990]"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteMICHELLERAMIREZHanggangKailan(Cassette1992)"] = "tsarcraft_music_01_62"
	GlobalMusic["CassettePOPSFERNANDEZAloneInTheRain(Cassette1984)"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteRACHELALEJANDROKayTagal(Cassette1989)"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteRACHELALEJANDROMrKupido(Cassette1989)"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteREYVALERABakaSakalingMahalinMoRin(Cassette1983)"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteSIDEAHoldOn(oncassette)"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteZSAZSAPADILLAWhenI'mWithYou(Cassette1985)"] = "tsarcraft_music_01_62"

